using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace GrcMvc.Filters;

/// <summary>
/// Action filter that makes the CSP nonce available to views via ViewData
/// The nonce is generated by SecurityHeadersMiddleware and stored in HttpContext.Items
/// </summary>
public class CspNonceFilter : IActionFilter
{
    public void OnActionExecuting(ActionExecutingContext context)
    {
        // Add CSP nonce to ViewData before action executes
        if (context.Controller is Controller controller)
        {
            var nonce = context.HttpContext.Items["CSPNonce"] as string;
            if (!string.IsNullOrEmpty(nonce))
            {
                controller.ViewData["CSPNonce"] = nonce;
            }
        }
    }

    public void OnActionExecuted(ActionExecutedContext context)
    {
        // No action needed after execution
    }
}
